apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: nanajanashia/argocd-app:1.2
        ports:
        - containerPort: 8080
        resources:
            requests:
              cpu: "100m"     # minimum 0.1 CPU
              memory: "128Mi" # minimum 128 MB
            limits:
              cpu: "200m"     # max 0.2 CPU
              memory: "256Mi" # max 256 MB
